# Generated by Django 2.2.4 on 2019-10-05 12:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('add', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=50)),
                ('orders', jsonfield.fields.JSONField(default=dict)),
                ('Price', models.IntegerField()),
                ('Status', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='TravelCustomize',
        ),
    ]
