# Generated by Django 2.2.4 on 2019-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191005_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitedfood',
            old_name='add',
            new_name='Add',
        ),
        migrations.RenameField(
            model_name='unitedfood',
            old_name='orders',
            new_name='Order',
        ),
        migrations.RemoveField(
            model_name='unitedfood',
            name='land',
        ),
        migrations.AlterField(
            model_name='unitedfood',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
